### ISSUE TITLE
Contact mistranslated

### ISSUE THREAD

**Issue by lxsameer** [Karajlug/karajlug_python#2]
This issue reported originally by 'AR-SOLI':

Instead of "ارتباط با ما" you used "ارتباط".

**Comment by ebraminio** [comment]
<div dir="rtl">
این مرج: https://github.com/Karajlug/karajlug/commit/9a59349857ac520067ae5ffb55b4d89f1120271a
<br />
این هم کامیت ترجمه که دو روز پیش دادم و اگه لاگتو نگاه کنی تو آی‌آرسی هم اومده: https://github.com/Karajlug/karajlug/commit/d0060055c7fdb25346be5530504af6c55ab532a6
</div>

**Comment by ebraminio** [comment]
Ops: https://github.com/Karajlug/karajlug/commit/d28146be93c48c6a68fd9450dddfb76e8626639e
